### ISSUE TITLE
Some irrelevant questions

### ISSUE THREAD

**Issue by Chenyuanyuan299** [datastructures-js/heap#38]
Hi, I'm learning how to implement heaps. Your heap implementation is very well written, but can you tell me in the extractRoot(), if the pop root == _leaf, _leaf will be the last node in _nodes, can it be directly assigned to null? What scenarios need to be assigned as this.root()?
next question, sort() will return a list in reverse order, and it mutates the node positions in the heap. This can be prevented in the code, can you tell me what you think?
Although it is a minor issue, I look forward to your reply, I would appreciate it. And I will provide a pr if necessary.

**Comment by eyas-ranjous** [comment]
hi @Chenyuanyuan299 sorry for the late reply

for 1. indeed, no need to assign to root when it's the last node being extracted. null is good. https://github.com/datastructures-js/heap/pull/39
for 2. do you mean creating a copy of the list being sorted inside the heap? if so, that was intentional in order not to create additional O(n) space, and leave that to the caller in case needed (`clone().sort()`) also,`fix()` can be called to fix positions after sorting the same instance.

**Comment by Chenyuanyuan299** [comment]
Ok, I got it, thank you very much.
